export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="/Users/matt/.local/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
